
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Random;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DOM
 */
public class bank extends javax.swing.JFrame {

    int htime = 0;
    Timer timer;
    Timer cooldown;
    
    int deck =1;
    int headnum =4;
    int bodynum =2;
    int buy1 ,buy2 ,buy3 ,buy4 ,buy5 ,buy6 ,buy7 ,buy8 ,buy9 ,buy10 =1 ,buy11 =1 ,buy12 =1;
    int code1 ,code2 ,code3 ,code4 ;
    int money =1000;
    int m_bank = 2000;
    int ticket =0;
    int ticketrandom =0;
    int sound ,effect;
    Timer lotteryR;
    Timer lotteryF;
    Timer lotteryW;
    
    public bank() {
        initComponents();
        
        setResizable(false);
        loadsave();
        bankBG.setIcon(new ImageIcon("src\\main\\java\\Image\\bank\\bank.png"));
        popup.hide();
        esc_popup.hide();
        ticketnum.hide();
        lot_rd.hide();
        //character
        head.setIcon(new ImageIcon("src\\main\\java\\Image\\character\\head"+(headnum)+"_1.png"));
        body.setIcon(new ImageIcon("src\\main\\java\\Image\\character\\body"+(bodynum)+".png"));
        htime = 0;
        delay();
        cooldown.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        esc_popup = new javax.swing.JLabel();
        lotteryno = new javax.swing.JLabel();
        lotteryyes = new javax.swing.JLabel();
        ticketnum = new javax.swing.JLabel();
        popup = new javax.swing.JLabel();
        esc = new javax.swing.JLabel();
        lot_rd = new javax.swing.JLabel();
        ticket1 = new javax.swing.JLabel();
        ticket2 = new javax.swing.JLabel();
        ticket3 = new javax.swing.JLabel();
        ticket4 = new javax.swing.JLabel();
        ticket5 = new javax.swing.JLabel();
        ticket6 = new javax.swing.JLabel();
        ticket7 = new javax.swing.JLabel();
        ticket8 = new javax.swing.JLabel();
        ticket9 = new javax.swing.JLabel();
        ticket10 = new javax.swing.JLabel();
        lottery_about = new javax.swing.JLabel();
        actionbox = new javax.swing.JTextField();
        bal_bank = new javax.swing.JLabel();
        bal = new javax.swing.JLabel();
        lottery = new javax.swing.JLabel();
        dep = new javax.swing.JLabel();
        with = new javax.swing.JLabel();
        withdep = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        body = new javax.swing.JLabel();
        bankBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BJ21");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        esc_popup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                esc_popupMouseClicked(evt);
            }
        });
        getContentPane().add(esc_popup, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 60, 50));

        lotteryno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lotterynoMouseClicked(evt);
            }
        });
        getContentPane().add(lotteryno, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 80, 70));

        lotteryyes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lotteryyesMouseClicked(evt);
            }
        });
        getContentPane().add(lotteryyes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 80, 70));

        ticketnum.setFont(new java.awt.Font("Source Sans Pro", 1, 30)); // NOI18N
        ticketnum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ticketnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 50, 45));

        popup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popupMouseClicked(evt);
            }
        });
        getContentPane().add(popup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 600));

        esc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escMouseClicked(evt);
            }
        });
        getContentPane().add(esc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 35));

        lot_rd.setFont(new java.awt.Font("Tahoma", 1, 135)); // NOI18N
        lot_rd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lot_rd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 230, 160));

        ticket1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticket1MouseClicked(evt);
            }
        });
        getContentPane().add(ticket1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 90, 50));

        ticket2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticket2MouseClicked(evt);
            }
        });
        getContentPane().add(ticket2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 90, 50));

        ticket3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticket3MouseClicked(evt);
            }
        });
        getContentPane().add(ticket3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 100, 40));

        ticket4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticket4MouseClicked(evt);
            }
        });
        getContentPane().add(ticket4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 90, 40));

        ticket5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticket5MouseClicked(evt);
            }
        });
        getContentPane().add(ticket5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 90, 50));

        ticket6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticket6MouseClicked(evt);
            }
        });
        getContentPane().add(ticket6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 90, 50));

        ticket7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticket7MouseClicked(evt);
            }
        });
        getContentPane().add(ticket7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 90, 50));

        ticket8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticket8MouseClicked(evt);
            }
        });
        getContentPane().add(ticket8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 100, 40));

        ticket9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticket9MouseClicked(evt);
            }
        });
        getContentPane().add(ticket9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 100, 50));

        ticket10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticket10MouseClicked(evt);
            }
        });
        getContentPane().add(ticket10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 90, 60));

        lottery_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lottery_aboutMouseClicked(evt);
            }
        });
        getContentPane().add(lottery_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 50, 50));

        actionbox.setFont(new java.awt.Font("BrowalliaUPC", 1, 48)); // NOI18N
        actionbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(actionbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 160, 42));

        bal_bank.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        bal_bank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bal_bank.setText("999999");
        getContentPane().add(bal_bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 220, 60));

        bal.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        bal.setForeground(new java.awt.Color(255, 204, 0));
        bal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bal.setText("$1000");
        getContentPane().add(bal, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 160, 50));

        lottery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lotteryMouseClicked(evt);
            }
        });
        getContentPane().add(lottery, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 170, 40));

        dep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depMouseClicked(evt);
            }
        });
        getContentPane().add(dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 130, 50));

        with.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withMouseClicked(evt);
            }
        });
        getContentPane().add(with, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 140, 50));

        withdep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withdepMouseClicked(evt);
            }
        });
        getContentPane().add(withdep, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 170, 40));
        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 170, 170));
        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, 120, 130));

        bankBG.setIcon(new javax.swing.ImageIcon("C:\\Users\\DOM\\Desktop\\21BlackJack\\src\\main\\java\\image\\bank\\bank.png")); // NOI18N
        getContentPane().add(bankBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void winsound() {
        try {
                File sound = new File("src\\main\\java\\sound\\mixkit-achievement-completed.wav");
                Clip clicksound = AudioSystem.getClip();
                clicksound.open(AudioSystem.getAudioInputStream(sound ));
                if (effect ==0) clicksound.start();
        } catch (Exception e) {
        }
    }
    
    public void rdsound() {
        try {
                File sound = new File("src\\main\\java\\sound\\mixkit-arcade-slot-machine-wheel.wav");
                Clip clicksound = AudioSystem.getClip();
                clicksound.open(AudioSystem.getAudioInputStream(sound ));
                if (effect ==0) clicksound.start();
        } catch (Exception e) {
        }
    }
    
    public void tabsound() {
        try {
                File sound = new File("src\\main\\java\\sound\\mixkit-arcade-game-jump-coin.wav");
                Clip clicksound = AudioSystem.getClip();
                clicksound.open(AudioSystem.getAudioInputStream(sound ));
                if (effect ==0) clicksound.start();
        } catch (Exception e) {
        }
    }
    
    public void errorsound() {
        try {
                File sound = new File("src\\main\\java\\sound\\mixkit-quick-lock.wav");
                Clip clicksound = AudioSystem.getClip();
                clicksound.open(AudioSystem.getAudioInputStream(sound ));
                if (effect ==0) clicksound.start();
        } catch (Exception e) {
        }
    }
    
    private void delay() {
         cooldown = new Timer (5000 , new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                 animation();
                 timer.start();
             }
     });
 } 
    
    private void animation() {
         timer = new Timer (200 , new ActionListener() {
             
             @Override
             public void actionPerformed(ActionEvent e) {
                 htime++ ;
                 head.setIcon(new ImageIcon("src\\main\\java\\Image\\character\\head"+(headnum)+"_"+(htime)+".png"));
                          if (htime >3) {
                           htime = 0;
                           head.setIcon(new ImageIcon("src\\main\\java\\Image\\character\\head"+(headnum)+"_1.png"));
                           timer.stop();
                          }
             }
     });
 } 
    
    private void escMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escMouseClicked
        tabsound();
        autosave();
        new screen().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_escMouseClicked
    private void lotteryON() {
        bankBG.setIcon(new ImageIcon("src\\main\\java\\Image\\bank\\lottery.png"));
        bal_bank.hide();
        actionbox.hide();
        dep.hide();
        with.hide();
        ticket1.show();
        ticket2.show();
        ticket3.show();
        ticket4.show();
        ticket5.show();
        ticket6.show();
        ticket7.show();
        ticket8.show();
        ticket9.show();
        ticket10.show();
        lottery_about.show();
    }

    private void bankON() {
        bankBG.setIcon(new ImageIcon("src\\main\\java\\Image\\bank\\bank.png"));
        bal_bank.show();
        actionbox.show();
        dep.show();
        with.show();
        ticket1.hide();
        ticket2.hide();
        ticket3.hide();
        ticket4.hide();
        ticket5.hide();
        ticket6.hide();
        ticket7.hide();
        ticket8.hide();
        ticket9.hide();
        ticket10.hide();
        lottery_about.hide();
    }

    private void lotteryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lotteryMouseClicked
        lotteryON();
        tabsound();
    }//GEN-LAST:event_lotteryMouseClicked

    private void withdepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdepMouseClicked
        bankON();
        tabsound();
    }//GEN-LAST:event_withdepMouseClicked

    private void depMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depMouseClicked
        tabsound();
        popup.setIcon(new ImageIcon("src\\main\\java\\Image\\bank\\bank_error.png"));
        int bankM = Integer.parseInt(actionbox.getText());
            try {
                            if(money  < bankM){
                                throw new Exception();
                            }
                             else if(bankM <= money) {
                                 money = money - bankM;
                                 m_bank = m_bank + bankM;
                                 bal.setText("$"+money);
                                 bal_bank.setText(""+m_bank);
                             }
                    } catch(Exception e) {
                        popuperror();
                        errorsound();
                    }
        actionbox.setText("");
        autosave();
    }//GEN-LAST:event_depMouseClicked

    private void withMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withMouseClicked
        tabsound();
        popup.setIcon(new ImageIcon("src\\main\\java\\Image\\bank\\bank_error.png"));
        int bankM = Integer.parseInt(actionbox.getText());
            try {
                            if(m_bank  < bankM){
                                throw new Exception();
                            }
                             else if(bankM <= m_bank) {
                                 money = money + bankM;
                                 m_bank = m_bank - bankM;
                                 bal.setText("$"+money);
                                 bal_bank.setText(""+m_bank);
                             }
                    } catch(Exception e) {
                        popuperror();
                        errorsound();
                    }
        actionbox.setText("");
        autosave();
    }//GEN-LAST:event_withMouseClicked

    private void esc_popupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esc_popupMouseClicked
        tabsound();
        popup.hide();
        esc_popup.hide();
    }//GEN-LAST:event_esc_popupMouseClicked

    private void lottery_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lottery_aboutMouseClicked
        popup.setIcon(new ImageIcon("src\\main\\java\\Image\\bank\\lottery_about.png"));
        popuperror();
        tabsound();
    }//GEN-LAST:event_lottery_aboutMouseClicked

    private void ticket1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticket1MouseClicked
        ticket = 1;
        lotterybuy();
    }//GEN-LAST:event_ticket1MouseClicked

    private void ticket2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticket2MouseClicked
        ticket = 2;
        lotterybuy();
    }//GEN-LAST:event_ticket2MouseClicked

    private void ticket3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticket3MouseClicked
       ticket = 3;
       lotterybuy();
    }//GEN-LAST:event_ticket3MouseClicked

    private void ticket4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticket4MouseClicked
        ticket = 4;
        lotterybuy();
    }//GEN-LAST:event_ticket4MouseClicked

    private void ticket5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticket5MouseClicked
        ticket = 5;
        lotterybuy();
    }//GEN-LAST:event_ticket5MouseClicked

    private void ticket6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticket6MouseClicked
        ticket = 6;
        lotterybuy();
    }//GEN-LAST:event_ticket6MouseClicked

    private void ticket7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticket7MouseClicked
       ticket = 7;
       lotterybuy();
    }//GEN-LAST:event_ticket7MouseClicked

    private void ticket8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticket8MouseClicked
        ticket = 8;
        lotterybuy();
    }//GEN-LAST:event_ticket8MouseClicked

    private void ticket9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticket9MouseClicked
        ticket = 9;
        lotterybuy();
    }//GEN-LAST:event_ticket9MouseClicked

    private void ticket10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticket10MouseClicked
        ticket = 10;
        lotterybuy();
    }//GEN-LAST:event_ticket10MouseClicked

    private void lotterynoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lotterynoMouseClicked
        tabsound();
        popup.hide();
        ticketnum.hide();  
        lotteryyes.hide();
        lotteryno.hide();
    }//GEN-LAST:event_lotterynoMouseClicked

    private void lotteryyesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lotteryyesMouseClicked
        tabsound();
        ticket1.hide();
        ticket2.hide();
        ticket3.hide();
        ticket4.hide();
        ticket5.hide();
        ticket6.hide();
        ticket7.hide();
        ticket8.hide();
        ticket9.hide();
        ticket10.hide();
        popup.hide();
                try {
                            if(money < 100){
                                throw new Exception();
                            }
                             else if(100 <= money) {
                                 money = money - 100;
                                 bal.setText("$"+money);
                                 autosave();
                                 lottery_random();
                             }
                    } catch(Exception e) {
                        popup.setIcon(new ImageIcon("src\\main\\java\\Image\\bank\\bank_error.png"));
                        popuperror();
                        errorsound();
                        lotteryON();
                    }
        ticketnum.hide();
        lotteryyes.hide();
        lotteryno.hide();
    }//GEN-LAST:event_lotteryyesMouseClicked

    private void popupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popupMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_popupMouseClicked

    private void lottery_random() {
        rdsound();
        bankBG.setIcon(new ImageIcon("src\\main\\java\\Image\\bank\\lottery_random.png"));
        lot_rd.show();
        randomlottery();
        lotteryR.start();
        findlottery();
        lotteryF.start();
        winerlottery();
        lotteryW.start();
    }

    private void randomlottery() {
         lotteryR = new Timer (150 , new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                    Random rd = new Random(); 
                    ticketrandom = 1+rd.nextInt(10);
                    lot_rd.setText(""+ticketrandom);
             }
     });
    }

    private void findlottery() {
         lotteryF = new Timer (1000 , new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                    lotteryR.stop();
                    Random rd = new Random(); 
                    ticketrandom = 1+rd.nextInt(10);
                    lot_rd.setText(""+ticketrandom); 
                    lotteryF.stop();
             }
     });
 }

    private void winerlottery() {
         lotteryW = new Timer (2000 , new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                 //ticketrandom = ticket;
                 if(ticket == ticketrandom) {
                     winsound();
                    popup.setIcon(new ImageIcon("src\\main\\java\\Image\\bank\\lottery_win.png"));
                    popuperror();
                    money = money+5000;
                    bal.setText("$"+money);
                 }
                 if(ticket != ticketrandom) {
                    popup.setIcon(new ImageIcon("src\\main\\java\\Image\\bank\\lottery_lose.png"));
                    popuperror();
                    errorsound();
                 }
                    lotteryON();
                    autosave();
                    lot_rd.hide();
                    lotteryW.stop();
             }
     });
 }
    
    private void popuperror() {
        popup.show();
        esc_popup.show();
}
    
    private void lotterybuy() {
        tabsound();
        ticketnum.show();
        ticketnum.setText(""+ticket);
        popup.setIcon(new ImageIcon("src\\main\\java\\Image\\bank\\lottery_buy.png"));
        popup.show();
        lotteryyes.show();
        lotteryno.show();
}
    
    private void autosave() {
        try {
            FileOutputStream fos = new FileOutputStream ("save.dat");
            BufferedOutputStream bos = new BufferedOutputStream (fos);
            ObjectOutputStream oos = new ObjectOutputStream (bos);
            
            data data = new data();
            
            data.money = money;
            data.headnum = headnum;
            data.bodynum = bodynum;
            data.m_bank = m_bank;
            data.sound = sound;
            data.effect = effect;
            data.deck = deck;
            data.buy1 = buy1;
            data.buy2 = buy2;
            data.buy3 = buy3;
            data.buy4 = buy4;
            data.buy5 = buy5;
            data.buy6 = buy6;
            data.buy7 = buy7;
            data.buy8 = buy8;
            data.buy9 = buy9;
            data.code1 = code1;
            data.code2 = code2;
            data.code3 = code3;
            data.code4 = code4;
            
            oos.writeObject(data);
            oos.close();
            
        } catch (IOException e) {
            System.out.println("Error :(");
        }
    }
        
    private void loadsave() {
        try {
            FileInputStream fis = new FileInputStream ("save.dat");
            BufferedInputStream bis = new BufferedInputStream (fis);
            ObjectInputStream ois = new ObjectInputStream (bis);
            
            data data = (data)ois.readObject();
            
            money = data.money;
            headnum = data.headnum;
            bodynum = data.bodynum;
            m_bank = data.m_bank;
            sound = data.sound;
            effect = data.effect;
            deck = data.deck;
            buy1 = data.buy1;
            buy2 = data.buy2;
            buy3 = data.buy3;
            buy4 = data.buy4;
            buy5 = data.buy5;
            buy6 = data.buy6;
            buy7 = data.buy7;
            buy8 = data.buy8;
            buy9 = data.buy9;
            code1 = data.code1;
            code2 = data.code2;
            code3 = data.code3;
            code4 = data.code4;
            
            ois.close();
            bal.setText("$"+money);
            bal_bank.setText(""+m_bank);
            
        } catch (IOException e) {
            System.out.println("Error load save... :(");
        } catch (ClassNotFoundException e) {
            System.out.println("Error load save... :(");
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actionbox;
    private javax.swing.JLabel bal;
    private javax.swing.JLabel bal_bank;
    private javax.swing.JLabel bankBG;
    private javax.swing.JLabel body;
    private javax.swing.JLabel dep;
    private javax.swing.JLabel esc;
    private javax.swing.JLabel esc_popup;
    private javax.swing.JLabel head;
    private javax.swing.JLabel lot_rd;
    private javax.swing.JLabel lottery;
    private javax.swing.JLabel lottery_about;
    private javax.swing.JLabel lotteryno;
    private javax.swing.JLabel lotteryyes;
    private javax.swing.JLabel popup;
    private javax.swing.JLabel ticket1;
    private javax.swing.JLabel ticket10;
    private javax.swing.JLabel ticket2;
    private javax.swing.JLabel ticket3;
    private javax.swing.JLabel ticket4;
    private javax.swing.JLabel ticket5;
    private javax.swing.JLabel ticket6;
    private javax.swing.JLabel ticket7;
    private javax.swing.JLabel ticket8;
    private javax.swing.JLabel ticket9;
    private javax.swing.JLabel ticketnum;
    private javax.swing.JLabel with;
    private javax.swing.JLabel withdep;
    // End of variables declaration//GEN-END:variables
}
