/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.WindowEvent;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.*;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;

/**
 *
 * @author DOM
 */
public class screen extends javax.swing.JFrame {
    
    int deck =1;
    int headnum =4;
    int bodynum =2;
    int money =1000;
    int m_bank = 2000;
    int buy1 ,buy2 ,buy3 ,buy4 ,buy5 ,buy6 ,buy7 ,buy8 ,buy9 ,buy10 =1 ,buy11 =1 ,buy12 =1;
    int code1 ,code2 ,code3 ,code4 ;
    int sound ,effect;

    public screen() {
        initComponents();
        
        loadsave();
        setResizable(false);
        jLabel1.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\menu_bg.png"));
        menu_update.setIcon(new ImageIcon("src\\main\\java\\Image\\menu_update.png"));
        menu_update.hide();
        fillcode.hide();
        txtgive.hide();
        s_sound.hide();
        update_esc.hide();
        head.setIcon(new ImageIcon("src\\main\\java\\Image\\character\\head"+(headnum)+"_1.png"));
        body.setIcon(new ImageIcon("src\\main\\java\\Image\\character\\body"+(bodynum)+".png"));
        head.hide();
        body.hide();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        update_esc = new javax.swing.JLabel();
        comfirm = new javax.swing.JLabel();
        txtgive = new javax.swing.JLabel();
        s_sound = new javax.swing.JLabel();
        fillcode = new javax.swing.JTextField();
        menu_update = new javax.swing.JLabel();
        bank = new javax.swing.JLabel();
        play = new javax.swing.JLabel();
        shop = new javax.swing.JLabel();
        option = new javax.swing.JLabel();
        code = new javax.swing.JLabel();
        minigame = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        body = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BJ21");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update_esc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_escMouseClicked(evt);
            }
        });
        getContentPane().add(update_esc, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 60, 50));

        comfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comfirmMouseClicked(evt);
            }
        });
        getContentPane().add(comfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 140, 60));

        txtgive.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txtgive.setForeground(new java.awt.Color(255, 153, 51));
        txtgive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtgive, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 320, 180));

        s_sound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s_sound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s_soundMouseClicked(evt);
            }
        });
        getContentPane().add(s_sound, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 110, 50));

        fillcode.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        fillcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(fillcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 310, 70));

        menu_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_updateMouseExited(evt);
            }
        });
        getContentPane().add(menu_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 600));

        bank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bankMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bankMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bankMouseExited(evt);
            }
        });
        getContentPane().add(bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 100, 100));

        play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playMouseExited(evt);
            }
        });
        getContentPane().add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 180, 150));

        shop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shopMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                shopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                shopMouseExited(evt);
            }
        });
        getContentPane().add(shop, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 110, 110));

        option.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optionMouseExited(evt);
            }
        });
        getContentPane().add(option, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 80, 90));

        code.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                codeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                codeMouseExited(evt);
            }
        });
        getContentPane().add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 100, 90));

        minigame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minigameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minigameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minigameMouseExited(evt);
            }
        });
        getContentPane().add(minigame, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 130, 140));

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 490, 100, 100));
        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 170, 170));
        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 120, 130));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DOM\\Desktop\\21BlackJack\\src\\main\\java\\image\\menu\\menu_bg.png")); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void warpsound() {
        try {
                File sound = new File("src\\main\\java\\sound\\mixkit-arcade-game-jump-coin.wav");
                Clip clicksound = AudioSystem.getClip();
                clicksound.open(AudioSystem.getAudioInputStream(sound ));
                if (effect ==0) clicksound.start();
        } catch (Exception e) {
        }
    }
    
    public void clicksound() {
        try {
                File sound = new File("src\\main\\java\\sound\\mixkit-soap-bubble.wav");
                Clip clicksound = AudioSystem.getClip();
                clicksound.open(AudioSystem.getAudioInputStream(sound ));
                if (effect ==0) clicksound.start();
        } catch (Exception e) {
        }
    }
    
    private void playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseClicked
        warpsound();
        autosave();
        new main().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_playMouseClicked

    private void optionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionMouseClicked
        setting();
        warpsound();
    }//GEN-LAST:event_optionMouseClicked

    private void shopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shopMouseClicked
        warpsound();
        autosave();
        new shop().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_shopMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        warpsound();
        autosave();
        //setVisible(false);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_exitMouseClicked

    private void update_escMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_escMouseClicked
        menu_update.setIcon(new ImageIcon("src\\main\\java\\Image\\menu_update.png"));
        txtgive.setIcon(new ImageIcon(""));
        menu_update.hide();
        fillcode.hide();
        txtgive.hide();
        s_sound.hide();
        warpsound();
        update_esc.hide();
    }//GEN-LAST:event_update_escMouseClicked

    private void menu_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_updateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_updateMouseClicked

    private void playMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseEntered
        clicksound();
        jLabel1.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\menu_casino.png"));
    }//GEN-LAST:event_playMouseEntered

    private void menu_updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_updateMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_updateMouseExited

    private void menu_updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_updateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_updateMouseEntered

    private void playMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseExited
        jLabel1.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\menu_bg.png"));
    }//GEN-LAST:event_playMouseExited

    private void shopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shopMouseEntered
        clicksound();
        jLabel1.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\menu_shop.png"));
    }//GEN-LAST:event_shopMouseEntered

    private void shopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shopMouseExited
        jLabel1.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\menu_bg.png"));
    }//GEN-LAST:event_shopMouseExited

    private void optionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionMouseEntered
        clicksound();
        jLabel1.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\menu_setting.png"));
    }//GEN-LAST:event_optionMouseEntered

    private void optionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionMouseExited
        jLabel1.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\menu_bg.png"));
    }//GEN-LAST:event_optionMouseExited

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        clicksound();
        jLabel1.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\menu_exit.png"));
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        jLabel1.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\menu_bg.png"));
    }//GEN-LAST:event_exitMouseExited

    private void bankMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bankMouseEntered
        clicksound();
        jLabel1.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\menu_bank.png"));
    }//GEN-LAST:event_bankMouseEntered

    private void bankMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bankMouseExited
        jLabel1.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\menu_bg.png"));
    }//GEN-LAST:event_bankMouseExited

    private void bankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bankMouseClicked
        warpsound();
        autosave();
        new bank().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bankMouseClicked

    private void codeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codeMouseClicked
        warpsound();
        menu_update.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\code.png"));
        menu_update.show();
        update_esc.show();
        fillcode.show();
    }//GEN-LAST:event_codeMouseClicked

    private void codeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codeMouseEntered
        clicksound();
        jLabel1.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\menu_code.png"));
    }//GEN-LAST:event_codeMouseEntered

    private void codeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codeMouseExited
        jLabel1.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\menu_bg.png"));
    }//GEN-LAST:event_codeMouseExited

    private void minigameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minigameMouseClicked
        warpsound();
        autosave();
        new minigame().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_minigameMouseClicked

    private void minigameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minigameMouseEntered
        clicksound();
        jLabel1.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\menu_minigame.png"));
    }//GEN-LAST:event_minigameMouseEntered

    private void minigameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minigameMouseExited
        jLabel1.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\menu_bg.png"));
    }//GEN-LAST:event_minigameMouseExited

    private void comfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comfirmMouseClicked
        warpsound();
        //code1  6405713 = give $5000
        try {
            if(! fillcode.getText().equals("6405713")) {
                menu_update.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\code_error.png"));
                throw new Exception();
            }
            if(code1 !=0) {
                menu_update.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\code_used.png"));
                throw new Exception();
            }
            else if(fillcode.getText().equals("6405713") && code1 ==0) {
                menu_update.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\code_give.png"));
                txtgive.show();
                fillcode.hide();
                txtgive.setText("$ 5000");
                money = money + 5000;
                code1 =1;
            }        
        }catch(Exception e) {
            fillcode.hide();
            txtgive.setText("");
            txtgive.setIcon(new ImageIcon(""));
        }
        //code2  freehead = give head_1
        if(fillcode.getText().equals("head")) {
                try {
                    if(! fillcode.getText().equals("head")) {
                        menu_update.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\code_error.png"));
                        throw new Exception();
                    }
                    if(code2 !=0) {
                        menu_update.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\code_used.png"));
                        throw new Exception();
                    }
                    else if(fillcode.getText().equals("head") && code2 ==0) {
                        menu_update.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\code_give.png"));
                        txtgive.show();
                        fillcode.hide();
                        txtgive.setText("");
                        txtgive.setIcon(new ImageIcon("src\\main\\java\\image\\character\\head1_1.png"));
                        buy3 =1;
                        code2 =1;
                    }        
                }catch(Exception e) {
                    fillcode.hide();
                    txtgive.setText("");
                    txtgive.setIcon(new ImageIcon(""));
                }
        }
        //code3  body = give body_1
        if(fillcode.getText().equals("body")) {
                try {
                    if(! fillcode.getText().equals("body")) {
                        menu_update.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\code_error.png"));
                        throw new Exception();
                    }
                    if(code3 !=0) {
                        menu_update.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\code_used.png"));
                        throw new Exception();
                    }
                    else if(fillcode.getText().equals("body") && code3 ==0) {
                        menu_update.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\code_give.png"));
                        txtgive.show();
                        fillcode.hide();
                        txtgive.setText("");
                        txtgive.setIcon(new ImageIcon("src\\main\\java\\image\\character\\body1.png"));
                        buy6 =1;
                        code3 =1;
                    }        
                }catch(Exception e) {
                    fillcode.hide();
                    txtgive.setText("");
                    txtgive.setIcon(new ImageIcon(""));
                }
        }
        //code4  BJ21 = give 10000
        if(fillcode.getText().equals("BJ21")) {
            try {
                if(! fillcode.getText().equals("BJ21")) {
                    menu_update.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\code_error.png"));
                    throw new Exception();
                }
                if(code4 !=0) {
                    menu_update.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\code_used.png"));
                    throw new Exception();
                }
                else if(fillcode.getText().equals("BJ21") && code4 ==0) {
                    menu_update.setIcon(new ImageIcon("src\\main\\java\\Image\\menu\\code_give.png"));
                    txtgive.show();
                    fillcode.hide();
                    txtgive.setText("$ 10000");
                    money = money + 10000;
                    code4 =1;
                }        
            }catch(Exception e) {
                fillcode.hide();
                txtgive.setText("");
                txtgive.setIcon(new ImageIcon(""));
            }
        }
        
        fillcode.setText("");
        autosave();
    }//GEN-LAST:event_comfirmMouseClicked

    private void s_soundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_soundMouseClicked
        warpsound();
        effect = effect+1;
        if(effect >1) effect=0;
        if(effect ==1) s_sound.setIcon(new ImageIcon("src\\main\\java\\Image\\off.png")) ;
        else if(effect ==0) s_sound.setIcon(new ImageIcon("src\\main\\java\\Image\\on.png")) ;
        warpsound();
    }//GEN-LAST:event_s_soundMouseClicked

    private void setting() {
        update_esc.show();
        menu_update.show();
        menu_update.setIcon(new ImageIcon("src\\main\\java\\Image\\setting.png"));
        s_sound.show();
        if(effect ==1) s_sound.setIcon(new ImageIcon("src\\main\\java\\Image\\off.png")) ;
        else if(effect ==0) s_sound.setIcon(new ImageIcon("src\\main\\java\\Image\\on.png")) ;
    }
    
    private void autosave() {
        try {
            FileOutputStream fos = new FileOutputStream ("save.dat");
            BufferedOutputStream bos = new BufferedOutputStream (fos);
            ObjectOutputStream oos = new ObjectOutputStream (bos);
            
            data data = new data();
            
            data.money = money;
            data.headnum = headnum;
            data.bodynum = bodynum;
            data.m_bank = m_bank;
            data.sound = sound;
            data.effect = effect;
            data.deck = deck;
            data.buy1 = buy1;
            data.buy2 = buy2;
            data.buy3 = buy3;
            data.buy4 = buy4;
            data.buy5 = buy5;
            data.buy6 = buy6;
            data.buy7 = buy7;
            data.buy8 = buy8;
            data.buy9 = buy9;
            data.code1 = code1;
            data.code2 = code2;
            data.code3 = code3;
            data.code4 = code4;
            
            oos.writeObject(data);
            oos.close();
            
        } catch (IOException e) {
            System.out.println("Error :(");
        }
    }
        
    private void loadsave() {
        try {
            FileInputStream fis = new FileInputStream ("save.dat");
            BufferedInputStream bis = new BufferedInputStream (fis);
            ObjectInputStream ois = new ObjectInputStream (bis);
            
            data data = (data)ois.readObject();
            
            money = data.money;
            headnum = data.headnum;
            bodynum = data.bodynum;
            m_bank = data.m_bank;
            sound = data.sound;
            effect = data.effect;
            deck = data.deck;
            buy1 = data.buy1;
            buy2 = data.buy2;
            buy3 = data.buy3;
            buy4 = data.buy4;
            buy5 = data.buy5;
            buy6 = data.buy6;
            buy7 = data.buy7;
            buy8 = data.buy8;
            buy9 = data.buy9;
            code1 = data.code1;
            code2 = data.code2;
            code3 = data.code3;
            code4 = data.code4;
            
            ois.close();
            
        } catch (IOException e) {
            System.out.println("Error load save... :(");
        } catch (ClassNotFoundException e) {
            System.out.println("create a new save... :(");
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        screen sc = new screen();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bank;
    private javax.swing.JLabel body;
    private javax.swing.JLabel code;
    private javax.swing.JLabel comfirm;
    private javax.swing.JLabel exit;
    private javax.swing.JTextField fillcode;
    private javax.swing.JLabel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel menu_update;
    private javax.swing.JLabel minigame;
    private javax.swing.JLabel option;
    private javax.swing.JLabel play;
    private javax.swing.JLabel s_sound;
    private javax.swing.JLabel shop;
    private javax.swing.JLabel txtgive;
    private javax.swing.JLabel update_esc;
    // End of variables declaration//GEN-END:variables
}
